### ISSUE TITLE
Enable 1:1 release.

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/vscode-bridge-to-kubernetes#3]
**Is your feature request related to a problem? Please describe.**

This extension is consumer for Bridge to kubernetes CLI. Currently, what we notice that this tool has `1:n` relationship with `b2k bridge to kubernetes` **_CLI versions which will be breaking for user if the future CLI contains a breaking change which will also require the VSCode as consuming to be changed as well._**

**Solution**

We have discussed this already and we have decided to go with `1:1` relationship between vscode release and the CLI.

Since the code is now decentralise, this will be beneficial for avoiding abrupt behaviour and proper versioning use for the vscode.

Thanks heaps and fyi - cc: @elenavillamil, @hsubramanianaks, @qpetraroia ❤️ 🙏 📓

**Comment by qpetraroia** [comment]
100% behind this. Let's make it happen 🤘

**Comment by Tatsinnit** [comment]
Thanks all it’s been release as first release form GitHub repo, https://github.com/Azure/vscode-bridge-to-kubernetes/pull/5

Cli version it is logged in is 1.0.20220816.2, thanks 🙏☕️🥷
