### ISSUE TITLE
Logging refactor/cleanup

### ISSUE THREAD

**Issue by elenavillamil** [Azure/vscode-bridge-to-kubernetes#32]
**Is your feature request related to a problem? Please describe.**
Currently VSCode extension logs a lot of telemetry and logs that may not be needed.

**Mention what platform you want to support the new feature**
All

**Describe the solution you'd like**
Remove any unneeded logs or repeat logs. Because we are new owners, this will require a prior evaluation of all logs to better understand logging of this code base and make best decisions on what to keep.

**Additional context**
This will also help remove privacy warnings.

**Comment by hsubramanianaks** [comment]
this is taken care by PR - https://github.com/Azure/vscode-bridge-to-kubernetes/pull/83
