### ISSUE TITLE
Can't connect to minikube

### ISSUE THREAD

**Issue by gmax79** [Azure/vscode-bridge-to-kubernetes#33]
Ubuntu 22.04
Minikube 1.29.0
Kubernets 1.26.1
VSCode: 1.75.1
Kubernetes plugin: v1.3.11
Bridge to kubernetes: 2.0.120230124

Kubernetes addon works, but bridge to kubernetes can't connect to cluster with error:
Failed to refresh the kubeconfig token: Error occurred during a cryptographic operation.

Open menu Error:
Failed to get the current context from the kubeconfig: No kubeconfig file found at path /home/maks/.kube/config

**Comment by elenavillamil** [comment]
Can you try copying your kube config to that path and try again?

**Comment by gmax79** [comment]
kube config exists in that path ( /home/maks/.kube/config )
`
maks@host:~$ cat /home/maks/.kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/maks/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 25 Feb 2023 00:33:32 UTC
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 25 Feb 2023 00:33:32 UTC
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/maks/.minikube/profiles/minikube/client.crt
    client-key: /home/maks/.minikube/profiles/minikube/client.key

maks@host:~$ ls -la /home/maks/.kube/config 
-rw------- 1 maks maks 821 Feb 25 00:33 /home/maks/.kube/config
`

**Comment by hsubramanianaks** [comment]
@gmax79 is this issue still happening? Please let me know, thank you.

**Comment by hsubramanianaks** [comment]
@gmax79 is this still happening ? Please let us know or feel free to close this issue. Thank you.
