### ISSUE TITLE
Refactor or removal of V1 / V2 Binary code logic.

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/vscode-bridge-to-kubernetes#4]
### **Background**

This repository is now decentralised and soon we will do a release with this repo which will be for the marketplace `1:1` mapping for vscode and `b2k cli` version.

Given the code has legacy meaningful code which evolved with time we want to be little surgical for this removal just so that we make sure we don’t include any breaking behaviours, this workitem is generated for the careful understanding and simplification of that logic of **Binary Manager**. Mostly likely will be fun to simplify some parts of this code where I think we can preserve `v2` logic and remove `v1` but key thing is to understand the logical behaviour which will directly resonate in the PR for sure.

The existence of V2 was always to improve the Binary download experience and mechanism.

### **Solution**

At an abstract level we can make clean one of the existing `BinaryManager` module with a clear `Promise`, which will also mean that we will end up re-accessing the existence of `IBinariesUtility` interface because previously it existed because of 2 respective `utility v1 and v2` modules which will no longer exist after this work. Regarding quick refactor design I would say we keep to DRY, non-repetitive, and use Promises for type checking, make sure any error gets bubbled to the top and gets pinged that way. In case while refactoring we can see scope of better error management then we should add `Errorable` class for any error handling which can grow as we improve this extension.

This work should be more focused on simplifying [`line 97`](https://github.com/Azure/vscode-bridge-to-kubernetes/blob/main/src/ExtensionRoot.ts#L97) 

```*.ts
        const binariesUtility: IBinariesUtility = BinariesManager.getBinariesUtility(this._logger, context, commandEnvironmentVariables, accountContextManager, expectedCLIVersion);
```

The module which contains the relevant logic is this: `BinariesManager.getBinariesUtility` 

I think the simplest solution would be we continue with `V2` behaviour **but** before we drop `V1` lets just make sure what are the key differences before we short-circuit that part of the code form this refactor.

Once the above is understood, it will be likely we can make this [`nested  if condition`](https://github.com/Azure/vscode-bridge-to-kubernetes/blob/e15fa3c0ab5b4c70d4f44174adf28ddb4c81a2b5/src/utility/VersionUtility.ts#L64) simpler as well.

Thanks heaps, ☕️💡 cc: @elenavillamil , @hsubramanianaks , @qpetraroia , @sabbour , @gambtho and @Vidya2606  and just as fyi @daniv-msft thank you.

**Comment by hsubramanianaks** [comment]
Closing this since this was taken care long time back. Thank you.
