### ISSUE TITLE
Failed to get routing manager deployment status

### ISSUE THREAD

**Issue by garyburgmann** [Azure/vscode-bridge-to-kubernetes#57]
**Describe the bug**
re: https://github.com/Azure/vscode-bridge-to-kubernetes/issues/58

I also see this every time on MacOS Monterey

```
Failed to establish a connection. Error: Failed to get routing manager deployment status - ran out of time : 'Failed to get routing manager deployment status: 'Oops... An unexpected error has occurred.'Please include the following Correlation ID when contacting support: '51998f9b-5d22-43fe-97d5-44a591e71d1f1689648728010:4ce86b08fabd'. '
```

**Mention the platform you are using**
For latest release: https://github.com/Azure/vscode-bridge-to-kubernetes/releases/tag/2.0.120230716
and previous release: https://github.com/Azure/vscode-bridge-to-kubernetes/releases/tag/2.0.120230525

**To Reproduce**
1. On MacOS invoke B2K using the VsCode Extension, see `'Failed to get routing manager deployment status: 'Oops... An unexpected error has occurred.'` -> error
2. On MacOS invoke B2K using [CLI](https://github.com/Azure/Bridge-To-Kubernetes#cli-tool-installation) -> works fine
3. On Debian invoke B2K using the VsCode Extension -> works fine
4. On Debian invoke B2K using [CLI](https://github.com/Azure/Bridge-To-Kubernetes#cli-tool-installation)-> works fine

**Expected behavior**
The VsCode extension invokes the CLI under the hood, `'Failed to get routing manager deployment status: 'Oops... An unexpected error has occurred.'` error should not occur.

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.5 -> issue
 - OS:  Debian Bullseye -> fine

**Additional context**
](https://github.com/Azure/vscode-bridge-to-kubernetes/issues/58)

**Comment by hsubramanianaks** [comment]
@garyburgmann Thanks for the details and the chat. Is this happening with latest release ```2.0.120230716``` or it happens for previous release as well ? Can you share the vscode logs for these please ? it would be in ```$HOME/.vscode-server/data/logs/20230718T093117/exthost1/mindaro.mindaro/*```.  Please let me know.

**Comment by garyburgmann** [comment]
@hsubramanianaks as above ^^^

```
Mention the platform you are using
For latest release: https://github.com/Azure/vscode-bridge-to-kubernetes/releases/tag/2.0.120230716
and previous release: https://github.com/Azure/vscode-bridge-to-kubernetes/releases/tag/2.0.120230525
```

**Comment by garyburgmann** [comment]
Also, not sure what u want from `$HOME/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host\fxr` ... working remotely on Debian works fine. But for the sake of argument:

```sh
~/ $ ls .vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/
7.0.7
```

It is invoking on MacOS, without using `Remote - SSH`, that is the problem.

**Comment by hsubramanianaks** [comment]
@garyburgmann Thanks, let's continue to discuss in this issue - https://github.com/Azure/vscode-bridge-to-kubernetes/issues/58#issuecomment-1661130443.

**Comment by hsubramanianaks** [comment]
Closing this since this is duplicate.
