### ISSUE TITLE
Exception while failing the extension "Failed to update dependencies: Request failed with status code 404"

### ISSUE THREAD

**Issue by larsf96** [Azure/vscode-bridge-to-kubernetes#81]
**Describe the bug**
When installing this extension, I see a red warning message "Failed to update dependencies: Request failed with status code 404"

The output of the file downloader is:
```
ERROR: Request failed with status code 404. Technical details: {"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n\tat e.exports (/Users/xxx/.vscode/extensions/mindaro-dev.file-downloader-1.0.13/dist/extension.js:1:10919)\n\tat e.exports (/Users/xxx/.vscode/extensions/mindaro-dev.file-downloader-1.0.13/dist/extension.js:1:13335)\n\tat y.<anonymous> (/Users/xxx/.vscode/extensions/mindaro-dev.file-downloader-1.0.13/dist/extension.js:1:3348)\n\tat y.emit (node:events:525:35)\n\tat y._processResponse (/Users/xxx/.vscode/extensions/mindaro-dev.file-downloader-1.0.13/dist/extension.js:1:47925)\n\tat ClientRequest._onNativeResponse (/Users/xxx/.vscode/extensions/mindaro-dev.file-downloader-1.0.13/dist/extension.js:1:43124)\n\tat Object.onceWrapper (node:events:628:26)\n\tat ClientRequest.emit (node:events:525:35)\n\tat HTTPParser.parserOnIncomingClient (node:_http_client:701:27)\n\tat HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\n\tat TLSSocket.socketOnData (node:_http_client:542:22)\n\tat TLSSocket.emit (node:events:513:28)\n\tat addChunk (node:internal/streams/readable:324:12)\n\tat readableAddChunk (node:internal/streams/readable:297:9)\n\tat Readable.push (node:internal/streams/readable:234:10)\n\tat TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":5000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.26.1"},"responseType":"stream","proxy":false,"method":"get","url":"https://bridgetokubernetes.blob.core.windows.net/zipv2/LKS/kubectl-osx-arm64.zip"},"status":404}
**Mention the platform you are using**
Mention what platform you are using (oss, vscode) and pick the corresponding label.
```
The extension seems to start a download of the file https://bridgetokubernetes.blob.core.windows.net/zipv2/LKS/kubectl-osx-arm64.zip which is not existing (anymore). 

**To Reproduce**
1. Start VS Code
2. Install Extension

**Expected behavior**
The installation should complete without exception

**Screenshots**
![Bildschirmfoto 2023-12-06 um 10 37 19](https://github.com/Azure/vscode-bridge-to-kubernetes/assets/12511431/ff0ae984-d4e9-4df4-ba69-84c9bae3ae59)

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.1
 - VS Code version 1.84.2

**Comment by hsubramanianaks** [comment]
@larsf96 Apologies for the inconvenience. We will fix this asap and keep you posted here.

**Comment by hsubramanianaks** [comment]
@larsf96 the 404 error is fixed but we are getting another failed dependencies error which we are looking into it. We will keep you posted about it.

**Comment by hsubramanianaks** [comment]
@larsf96 While we work on getting this worked, you can always revert to previous version of extension and unblock yourself. we will let you know once this is fixed. Thanks for your patience.

**Comment by hsubramanianaks** [comment]
@erceth and @larsf96 This is related to https://github.com/Azure/Bridge-To-Kubernetes/issues/345, we will be releasing a new version soon and you can test beta version of it here - https://github.com/Azure/Bridge-To-Kubernetes/pull/346#issuecomment-1865213295. Please let me know how it goes. Thank you.

**Comment by hsubramanianaks** [comment]
@erceth @larsf96 This is released to production, please retest and close this issue. Thank you.

**Comment by larsf96** [comment]
Hi @hsubramanianaks 
I've just updated the VS code plugin to the latest version, but now I see the following error:
`Failed to update dependencies: Failed to load /Users/lars.fahrin/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, error: dlopen(/Users/lars.fahrin/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib, 0x0001): tried: '/Users/lars.fahrin/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/host/fxr/7.0.7/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),`

**Comment by hsubramanianaks** [comment]
@larsf96 Please follow these instructions and let me know how it goes. Thanks for trying this out.

https://github.com/Azure/Bridge-To-Kubernetes/issues/350#issuecomment-1889706656

**Comment by larsf96** [comment]
Hi @hsubramanianaks 
Thanks for the instructions. After deleting the old files everything worked fine with the latest release.
I'll close this issue, thanks for your support! :)
